import React from 'react';
import { SectionTitle } from '../components/ui/SectionTitle';
import { Card } from '../components/ui/Card';
import { AlertTriangle, Info, ShieldCheck } from 'lucide-react';

const Disclaimer: React.FC = () => {
  return (
    <main className="flex-1 overflow-y-auto p-6 md:p-10 max-w-4xl mx-auto w-full">
      <SectionTitle subtitle="Legal Documentation">Disclaimer</SectionTitle>

      <div className="space-y-8 text-text-secondary leading-relaxed animate-in fade-in duration-500">
        <section className="space-y-6">
          <Card className="p-6 border-warning/30 bg-warning/5 flex gap-4 items-start">
            <div className="p-2 bg-warning/20 rounded-full shrink-0">
              <AlertTriangle className="text-warning" size={20} />
            </div>
            <div>
              <h3 className="font-bold text-text-primary mb-1 uppercase text-sm tracking-wider">Educational Purposes Only</h3>
              <p className="text-sm">
                SeekFlow is intended strictly for educational and instructional purposes.
                The simulations, visualizations, and metrics provided are simplified
                representations of theoretical concepts.
              </p>
            </div>
          </Card>

          <div className="space-y-4">
            <h3 className="text-xl font-bold text-text-primary uppercase tracking-tight flex items-center gap-2">
              <span className="w-1 h-5 bg-primary rounded-full"></span>
              Algorithm Implementation
            </h3>
            <p>
              The algorithms implemented in SeekFlow (FCFS, SSTF, SCAN, C-SCAN, LOOK, C-LOOK)
              follow standard academic definitions. However, real-world Operating System
              kernels and disk controller firmwares use highly optimized, complex versions
              of these algorithms that may include proprietary heuristics not modeled here.
            </p>
          </div>

          <div className="space-y-4">
            <h3 className="text-xl font-bold text-text-primary uppercase tracking-tight flex items-center gap-2">
              <span className="w-1 h-5 bg-secondary rounded-full"></span>
              Accuracy and Reliability
            </h3>
            <p>
              While we make every effort to ensure the accuracy of the calculations and
              visualizations, SeekFlow makes no guarantees regarding the precision or
              reliability of the outputs. Results generated by this application should
              not be considered production-grade storage recommendations or benchmarks
              for actual hardware performance.
            </p>
          </div>

          <div className="space-y-4">
            <h3 className="text-xl font-bold text-text-primary uppercase tracking-tight flex items-center gap-2">
              <span className="w-1 h-5 bg-success rounded-full"></span>
              Independent Verification
            </h3>
            <p>
              Users are strongly encouraged to independently verify critical calculations.
              SeekFlow is not responsible for any decisions made based on the information
              provided by this tool. The "Detailed Analysis" and "PDF Reports" are provided
              to facilitate learning and comparison, not as definitive engineering data.
            </p>
          </div>
        </section>

        <section className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-4">
           <div className="p-4 bg-surface rounded-sm border border-border flex gap-3 items-center">
             <ShieldCheck className="text-success shrink-0" size={18} />
             <span className="text-xs uppercase font-mono">No Warranties Implied</span>
           </div>
           <div className="p-4 bg-surface rounded-sm border border-border flex gap-3 items-center">
             <Info className="text-secondary shrink-0" size={18} />
             <span className="text-xs uppercase font-mono">Theoretical Models Only</span>
           </div>
        </section>
      </div>
    </main>
  );
};

export default Disclaimer;
